//@version=6
library("three_white_soldier")

var int lookback = input.int(100, title = "Lookback")

if barstate.islast
	var int idx = 0
	for var int i = 0 to lookback - 2
		var int snd = i + 1
		var int thrd = i + 2

		if close[i] > open[i] and close[snd] > open[snd] and close[thrd] > open[thrd]
			box.new(left = bar_index - thrd, right = bar_index - i, bottom = math.min(low[i], low[snd], low[thrd]), top = math.max(high[i], high[snd], high[thrd]))

			break
