//@version=6
library("bar")

import JackisaDayTrader/err/1
import JackisaDayTrader/util/1

export type Rng
	float high
	float low

export type Bar
	Rng body
	Rng wick

export type Tag
	int idx
	string s

export bull(int offset) =>
	if offset < 0
		err.print(err.Err.idx_neg)

		na

	if offset < 1
		err.print(err.Err.idx_small)

		na

	close[i] > open[i]

export bear(int offset) =>
	if offset < 0
		err.print(err.Err.idx_neg)

		na

	if offset < 1
		err.print(err.Err.idx_small)

		na

	if close[i] < open[i]

export inside(int offset) =>
	if offset < 0
		err.print(err.Err.idx_neg)

		na

	if offset < 2
		err.print(err.Err.idx_small)

		na

	util.body_floor(i) > util.body_floor(idx_fst) and util.body_roof(i) < util.body_roof(idx_fst)

export doji(int offset) =>
	if offset < 0
		err.print(err.Err.idx_neg)

		na

	if offset < 1
		err.print(err.Err.idx_small)

		na

	close[i] == open[i]

export doji_gravestone(int offset) =>
	if offset < 0
		err.print(err.Err.idx_neg)

		na

	if offset < 1
		err.print(err.Err.idx_small)

		na

	doji(i) and low[i] == open[i] and high[i] != open[i]

export doji_one_legged(int offset) =>
	if offset < 0
		err.print(err.Err.idx_neg)

		na

	if offset < 1
		err.print(err.Err.idx_small)

		na

	float mid = open[i]
	close[i] == mid and (low[i] != mid or high[i] != mid)
	
export hammer_inverted(int offset) =>
	if offset < 0
		err.print(err.Err.idx_neg)

		na

	if offset < 1
		err.print(err.Err.idx_small)

		na

	float open_curr = open[i]
	float close_curr = close[i]

	high[i] - math.max(open_curr, close_curr) > math.abs(open_curr - close_curr)

export high_wave(int offset) =>
	if offset < 0
		err.print(err.Err.idx_neg)

		na

	if offset < 1
		err.print(err.Err.idx_small)

		na

	high[i] - low[i] >= (close[i] - open[i]) * 2

export pinbar(int offset) =>
	if offset < 0
		err.print(err.Err.idx_neg)

		na

	if offset < 1
		err.print(err.Err.idx_small)

		na

	math.abs(high[i] - low[i]) >= math.abs(close[i] - open[i]) * (2 / 3)
