//@version=6
library("bar")

import JackisaDayTrader/err/1
import JackisaDayTrader/util/1

export type Rng
	float high
	float low

export type Bar
	Rng body
	Rng wick

export type Tag
	int idx
	string s

export bull(int offset) =>
	if offset < 0
		err.print(err.Err.idx_neg)

		na

	if offset < 1
		err.print(err.Err.idx_small)

		na

	close[offset] > open[offset]

export bear(int offset) =>
	if offset < 0
		err.print(err.Err.idx_neg)

		na

	if offset < 1
		err.print(err.Err.idx_small)

		na

	close[offset] < open[offset]

export inside(int offset) =>
	if offset < 0
		err.print(err.Err.idx_neg)

		na

	if offset < 2
		err.print(err.Err.idx_small)

		na

	util.body_floor(i) > util.body_floor(idx_fst) and util.body_roof(i) < util.body_roof(idx_fst)

export doji(int offset) =>
	if offset < 0
		err.print(err.Err.idx_neg)

		na

	if offset < 1
		err.print(err.Err.idx_small)

		na

	close[offset] == open[offset]

export doji_gravestone(int offset) =>
	if offset < 0
		err.print(err.Err.idx_neg)

		na

	if offset < 1
		err.print(err.Err.idx_small)

		na

	doji(offset) and low[offset] == open[offset] and high[offset] != open[offset]

export doji_one_legged(int offset) =>
	if offset < 0
		err.print(err.Err.idx_neg)

		na

	if offset < 1
		err.print(err.Err.idx_small)

		na

	float mid = open[offset]
	close[offset] == mid and (low[offset] != mid or high[offset] != mid)
	
export hammer_inverted(int offset) =>
	if offset < 0
		err.print(err.Err.idx_neg)

		na

	if offset < 1
		err.print(err.Err.idx_small)

		na

	float open_curr = open[offset]
	float close_curr = close[offset]

	high[offset] - math.max(open_curr, close_curr) > math.abs(open_curr - close_curr)

export high_wave(int offset) =>
	if offset < 0
		err.print(err.Err.idx_neg)

		na

	if offset < 1
		err.print(err.Err.idx_small)

		na

	high[offset] - low[offset] >= (close[offset] - open[offset]) * 2

export pinbar(int offset) =>
	if offset < 0
		err.print(err.Err.idx_neg)

		na

	if offset < 1
		err.print(err.Err.idx_small)

		na

	math.abs(high[offset] - low[offset]) >= math.abs(close[offset] - open[offset]) * (2 / 3)
