//@version=6
library("bar_pattern")

import JackisaDayTrader/bar/1
import JackisaDayTrader/zone/1

export shark(int offset)
	if offset < 0
		err.print(err.Err.idx_neg)

		na

	if offset < 3
		err.print(err.Err.idx_small)

		na

	var int idx = 0
	for var int i = 2 to offset
		var int snd = i - 1
		var int thrd = i - 2

		bar.Tag[] offset = array.new<bar.Tag>()
		if open[thrd] < open[snd] and close[thrd] > close[snd] and open[snd] < open[i] and close[snd] > close[i]
			array.push(offset(bar.Tag.new(i, "Shark")))

	offset

export bos(int offset)
	if offset < 0
		err.print(err.Err.idx_neg)

		na

	if offset < 2
		err.print(err.Err.idx_small)

		na

	bar.Tag[] offset = array.new<bar.Tag>()
	for int i = 0 to offset
		if low[i] < low
			array.push(offset, bar.Tag.new(i, "Break of Structure"))

	offset

export three_white_soldier(int offset)
	if offset < 0
		err.print(err.Err.idx_neg)

		na

	if offset < 2
		err.print(err.Err.idx_small)

		na

	var int idx = 0
	for var int i = 0 to offset - 2
		var int snd = i + 1
		var int thrd = i + 2

		if close[i] > open[i] and close[snd] > open[snd] and close[thrd] > open[thrd]
			zone.Zone.new(bar_index[thrd], bar_index[i], math.min(low[i], low[snd], low[thrd]), math.max(high[i], high[snd], high[thrd]))

			break

export candle_bull_engulf(int offset)
	if offset < 0
		err.print(err.Err.idx_neg)

		na

	if offset < 2
		err.print(err.Err.idx_small)

		na

	bar.Tag[] offset = array.new<bar.Tag>()
	for var int i = 0 to offset
		if (close[i + 1] < open[i + 1]) and (close[i] > open[i]) and ((open[i] < open[i + 1]) and (close[i] > close[i + 1]))
			array.push(offset, bar.Tag.new(bar_index[i], "Bullish Engulfing Bar"))

	offset

export candle_bear_engulf(int offset)
	if offset < 0
		err.print(err.Err.idx_neg)

		na

	if offset < 2
		err.print(err.Err.idx_small)

		na

	bar.Tag[] offset = array.new<bar.Tag>()
	for var int i = 0 to offset
		if (close[i + 1] > open[i + 1]) and (close[i] < open[i]) and ((open[i] < open[i + 1]) and (close[i] > close[i + 1]))
			array.push(offset, bar.Tag.new(bar_index[i], "Bullish Engulfing Bar"))

	offset

export fvg_bull(int offset)
	if offset < 0
		err.print(err.Err.idx_neg)

		na

	if offset < 3
		err.print(err.Err.idx_small)

		na

	bar.Tag[] offset = array.new<bar.Tag>()
	for var int i = 0 to offset
		if close[i] < open[i - 2]
			array.push(offset, bar.Tag.new(bar_index[i], "Fair Value Gap"))

	offset

export tweezer_btm(int offset) =>
	if offset < 0
		err.print(err.Err.idx_neg)

		na

	if offset < 2
		err.print(err.Err.idx_small)

		na

	bar.Tag[] offset = array.new<bar.Tag>()
	for var int i = 0 to offset
		if low[i - 1] == low[i]
			array.push(offset, bar.Tag.new(i, "Tweezer Bottom"))

	offset
