//@version=6
library("bar_pattern")

import JackisaDayTrader/bar/1
import JackisaDayTrader/zone/1

type Rng
	float high
	float low

type Pattern
	Rng body
	Rng wick

export shark(int lookback)
	if lookback < 0
		err.print_enum(err.Err.idx_neg)

		na

	if lookback < 3
		err.print_enum(err.Err.idx_small)

		na

	var int idx = 0
	for var int i = 0 to lookback - 2
		var int snd = i + 1
		var int thrd = i + 2

		bar.Tag[] offset = array.new<bar.Tag>()
		if open[thrd] < open[snd] and close[thrd] > close[snd] and open[snd] < open[i] and close[snd] > close[i]
			array.push(offset(bar.Tag.new(i, "Shark")))

	offset

export bos(int lookback)
	bar.Tag[] offset = array.new<bar.Tag>()
	for int i = 0 to lookback
		if low[i] < low
			array.push(offset, bar.Tag.new(i, "Break of Structure"))

	offset

export three_white_soldier(int lookback)
	var int idx = 0
	for var int i = 0 to lookback - 2
		var int snd = i + 1
		var int thrd = i + 2

		if close[i] > open[i] and close[snd] > open[snd] and close[thrd] > open[thrd]
			zone.Zone.new(bar_index[thrd], bar_index[i], math.min(low[i], low[snd], low[thrd]), math.max(high[i], high[snd], high[thrd]))

			break

export candle_bull_engulf(int lookback)
	if lookback < 0
		err.print_enum(err.Err.idx_neg)

		na

	if lookback < 2
		err.print_enum(err.Err.idx_small)

		na

	bar.Tag[] offset = array.new<bar.Tag>()
	for var int i = 0 to lookback
		if (close[i + 1] < open[i + 1]) and (close[i] > open[i]) and ((open[i] < open[i + 1]) and (close[i] > close[i + 1]))
			array.push(offset, bar.Tag.new(bar_index[i], "Bullish Engulfing Bar"))

	offset

export candle_bear_engulf(int lookback)
	if lookback < 0
		err.print_enum(err.Err.idx_neg)

		na

	if lookback < 2
		err.print_enum(err.Err.idx_small)

		na

	bar.Tag[] offset = array.new<bar.Tag>()
	for var int i = 0 to lookback
		if (close[i + 1] > open[i + 1]) and (close[i] < open[i]) and ((open[i] < open[i + 1]) and (close[i] > close[i + 1]))
			array.push(offset, bar.Tag.new(bar_index[i], "Bullish Engulfing Bar"))

	offset

export fvg(int lookback)
	if lookback < 0
		err.print_enum(err.Err.idx_neg)

		na

	if lookback < 3
		err.print_enum(err.Err.idx_small)

		na

	bar.Tag[] offset = array.new<bar.Tag>()
	for var int i = 0 to lookback
		if open[i] > close[i + 2]
			array.push(offset, bar.Tag.new(bar_index[i], "Fair Value Gap"))

	offset

export tweezer_btm(int lookback) =>
	if lookback < 0
		err.print_enum(err.Err.idx_neg)

		na

	if lookback < 2
		err.print_enum(err.Err.idx_small)

		na

	bar.Tag[] offset = array.new<bar.Tag>()
	for var int i = 0 to lookback
		int idx_fst = i + 1
		if low[idx_fst] == low[i]
			array.push(offset, bar.Tag.new(idx_fst, "Tweezer Bottom"))

	offset
