//@version=6
library("bar_pattern")

import JackisaDayTrader/bar/1
import JackisaDayTrader/zone/1

export shark(int offset)
	if offset < 0
		err.print(err.Err.idx_neg)

		na

	if offset < 3
		err.print(err.Err.idx_small)

		na

	var int snd = offset - 1
	var int thrd = offset - 2
	open[thrd] < open[snd] and close[thrd] > close[snd] and open[snd] < open[offset] and close[snd] > close[offset]

export bos_bull(int offset, int ln)
	if offset < 0
		err.print(err.Err.idx_neg)

		na

	if offset < 2
		err.print(err.Err.idx_small)

		na

	if ln < 0
		err.print(err.Err.ln_neg)

		na

	bar.Tag[] offset = array.new<bar.Tag>()
	for var int i = offset to offset - ln by -1
		if high[i] > high
			offset.push(bar.Tag.new(i, "Break of Structure (Bullish)"))

	offset

export bos_bear(int offset, int ln)
	if offset < 0
		err.print(err.Err.idx_neg)

		na

	if offset < 2
		err.print(err.Err.idx_small)

		na

	if ln < 0
		err.print(err.Err.ln_neg)

		na

	bar.Tag[] offset = array.new<bar.Tag>()
	for var int i = offset to offset - ln by -1
		if low[i] < low
			offset.push(bar.Tag.new(i, "Break of Structure (Bearish)"))

	offset

export three_white_soldier(int offset)
	if offset < 0
		err.print(err.Err.idx_neg)

		na

	if offset < 2
		err.print(err.Err.idx_small)

		na

	var int snd = i + 1
	var int thrd = i + 2
	close[i] > open[i] and close[snd] > open[snd] and close[thrd] > open[thrd]

export candle_bull_engulf(int offset)
	if offset < 0
		err.print(err.Err.idx_neg)

		na

	if offset < 2
		err.print(err.Err.idx_small)

		na

	var int snd = i + 1
	(close[snd] < open[snd]) and (close[i] > open[i]) and ((open[i] < open[snd]) and (close[i] > close[snd]))

export candle_bear_engulf(int offset)
	if offset < 0
		err.print(err.Err.idx_neg)

		na

	if offset < 2
		err.print(err.Err.idx_small)

		na

	var int snd = i + 1
	(close[snd] > open[snd]) and (close[i] < open[i]) and ((open[i] < open[snd]) and (close[i] > close[snd]))

export fvg_bull(int offset)
	if offset < 0
		err.print(err.Err.idx_neg)

		na

	if offset < 3
		err.print(err.Err.idx_small)

		na

	close[i] < open[i - 2]

export fvg_bear(int offset)
	if offset < 0
		err.print(err.Err.idx_neg)

		na

	if offset < 3
		err.print(err.Err.idx_small)

		na

	close[i] > open[i - 2]

export tweezer_top(int offset) =>
	if offset < 0
		err.print(err.Err.idx_neg)

		na

	if offset < 2
		err.print(err.Err.idx_small)

		na

	if high[i] == high[i - 1]

export tweezer_btm(int offset) =>
	if offset < 0
		err.print(err.Err.idx_neg)

		na

	if offset < 2
		err.print(err.Err.idx_small)

		na

	if low[i] == low[i - 1]

export swing_high(int offset)
	if offset < 0
		err.print(err.Err.idx_neg)

		na

	if offset < 3
		err.print(err.Err.idx_small)

		na

	var float mid = high[offset - 1]
	high[offset] < mid and mid > high[offset - 2]
	
export swing_low(int offset)
	if offset < 0
		err.print(err.Err.idx_neg)

		na

	if offset < 3
		err.print(err.Err.idx_small)

		na

	var float mid = low[offset - 1]
	low[offset] > mid and mid < low[offset - 2]
