//@version=6
library("candle_bull_engulf")

var roof = input.int(100, "Roof", minval = 1, maxval = 300000)

if bar_index < 0
	0

if barstate.islast
  var int idx = 0
  for var int i = 0 to roof - 1
    if (close[i + 1] < open[i + 1]) and (close[i] > open[i]) and ((open[i] < open[i + 1]) and (close[i] > close[i + 1]))
    	idx := i

      break

	label.new(bar_index + idx, high[idx], "Bullish Engulfing Candle")
