//@version=6
library("candle_pattern")

import JackisaDayTrader/candle/1
import JackisaDayTrader/zone/1

type Pattern
	Rng body
	Rng wick

export shark(int lookback)
	var int idx = 0
	for var int i = 0 to lookback - 2
		if lookback < 0
			err.print("Index not natural number")

			na

		if lookback < 3
			err.print("Index too small to accomodate size of pattern")

			na

	var int snd = i + 1
	var int thrd = i + 2

	Tag[] offset = array.new<Tag>()
	if open[thrd] < open[snd] and close[thrd] > close[snd] and open[snd] < open[i] and close[snd] > close[i]
		array.push(offset(Tag.new(i, "Shark")))

	offset

export bos(int lookback)
	int idx = 0
	int old_bar_idx = last_bar_index - lookback
	for int i = 0 to lookback
		float low_curr = low[i]
		
		if low_curr < low[0]
			idx := i

			break

	label.new(last_bar_index[idx], low[idx], yloc = yloc.abovebar)

export three_white_soldier(int lookback)
	var int idx = 0
	for var int i = 0 to lookback - 2
	var int snd = i + 1
	var int thrd = i + 2

	if close[i] > open[i] and close[snd] > open[snd] and close[thrd] > open[thrd]
		zone.Zone.new(bar_index - thrd, bar_index - i, math.min(low[i], low[snd], low[thrd]), math.max(high[i], high[snd], high[thrd]))

		break
