//@version=6
library("candle")

import JackisaDayTrader/err/1
import JackisaDayTrader/util/1

export type Label
	int idx
	string str

export doji(int lookback) =>
	if lookback < 0
		err.print("Index not natural number")

		na

	int[] offset = array.new<int>()
	for var int i = 0 to lookback
		if close[i] == open[i]
			array.push(offset, i)

	offset

export inside(int lookback) =>
	if lookback < 0
		err.print("Index not natural number")

		na

	if lookback < 2
		err.print("Index too small to accomodate size of pattern")

		na

	int[] offset = array.new<int>()
	for var int i = 0 to lookback
		if util.body_floor(i) > util.body_floor(idx_fst) and util.body_roof(i) < util.body_roof(idx_fst)
			array.push(offset, i)

	offset

export bull(int lookback) =>
	if lookback < 0
		err.print("Index not natural number")

		na

	int[] offset = array.new<int>()
	for var int i = 0 to lookback
		if close[i] > open[i]
			array.push(offset, i)

	offset

export bear(int lookback) =>
	if lookback < 0
		err.print("Index not natural number")

		na

	int[] offset = array.new<int>()
	for var int i = 0 to lookback
		if close[i] < open[i]
			array.push(offset, i)

	offset
