//@version=6
library("candle")

import JackisaDayTrader/err/1
import JackisaDayTrader/util/1

export type Label
	int idx
	string str

export bull(int lookback) =>
	if lookback < 0
		err.print("Index not natural number")

		na

	Label[] offset = array.new<Label>()
	for var int i = 0 to lookback
		if close[i] > open[i]
			array.push(offset, Label.new(i, "Bullish Candle"))

	offset

export bear(int lookback) =>
	if lookback < 0
		err.print("Index not natural number")

		na

	Label[] offset = array.new<Label>()
	for var int i = 0 to lookback
		if close[i] < open[i]
			array.push(offset, Label.new(i, "Bearish Candle"))

	offset

export inside(int lookback) =>
	if lookback < 0
		err.print("Index not natural number")

		na

	if lookback < 2
		err.print("Index too small to accomodate size of pattern")

		na

	Label[] offset = array.new<Label>()
	for var int i = 0 to lookback
		int idx_fst = i + 1
		if util.body_floor(i) > util.body_floor(idx_fst) and util.body_roof(i) < util.body_roof(idx_fst)
			array.push(offset, Label.new(i, "Inside Candle"))

	offset

export doji(int lookback) =>
	if lookback < 0
		err.print("Index not natural number")

		na

	Label[] offset = array.new<Label>()
	for var int i = 0 to lookback
		if close[i] == open[i]
			array.push(offset, Label.new(i, "Doji Candle"))

	offset
