//@version=6
library("candle")

import JackisaDayTrader/err/1
import JackisaDayTrader/util/1

export type Tag
	int idx
	string str

export bull(int lookback) =>
	if lookback < 0
		err.print("Index not natural number")

		na

	if lookback < 1
		err.print("Index too small to accomodate size of pattern")

		na

	Tag[] offset = array.new<Tag>()
	for var int i = 0 to lookback
		if close[i] > open[i]
			array.push(offset, Tag.new(i, "Bullish Candle"))

	offset

export bear(int lookback) =>
	if lookback < 0
		err.print("Index not natural number")

		na

	if lookback < 1
		err.print("Index too small to accomodate size of pattern")

		na

	Tag[] offset = array.new<Tag>()
	for var int i = 0 to lookback
		if close[i] < open[i]
			array.push(offset, Tag.new(i, "Bearish Candle"))

	offset

export inside(int lookback) =>
	if lookback < 0
		err.print("Index not natural number")

		na

	if lookback < 2
		err.print("Index too small to accomodate size of pattern")

		na

	Tag[] offset = array.new<Tag>()
	for var int i = 0 to lookback
		int idx_fst = i + 1
		if util.body_floor(i) > util.body_floor(idx_fst) and util.body_roof(i) < util.body_roof(idx_fst)
			array.push(offset, Tag.new(i, "Inside Candle"))

	offset

export doji(int lookback) =>
	if lookback < 0
		err.print("Index not natural number")

		na

	if lookback < 1
		err.print("Index too small to accomodate size of pattern")

		na

	Tag[] offset = array.new<Tag>()
	for var int i = 0 to lookback
		if close[i] == open[i]
			array.push(offset, Tag.new(i, "Doji Candle"))

	offset

export doji_gravestone(int lookback) =>
	if lookback < 0
		err.print("Index not natural number")

		na

	if lookback < 1
		err.print("Index too small to accomodate size of pattern")

		na

	Tag[] offset = array.new<Tag>()
	for var int i = 0 to lookback
		float mid = open[i]
		if close[i] == mid and low[i] == mid and high[i] != mid
			array.push(offset, Tag.new(i, "Gravestone Doji Candle"))

	offset

export doji_one_legged(int lookback) =>
	if lookback < 0
		err.print("Index not natural number")

		na

	if lookback < 1
		err.print("Index too small to accomodate size of pattern")

		na

	Tag[] offset = array.new<Tag>()
	for var int i = 0 to lookback
		float mid = open[i]
		if close[i] == mid and (low[i] != mid or high[i] != mid)
			array.push(offset, Tag.new(i, "Gravestone Doji Candle"))

		offset
