//@version=6
indicator("trend")

var roof = input.int(100, "Roof", minval = 1, maxval = 300000)

if bar_index < 0
	0

if barstate.islast
	var float lower_low = low[roof]
	var bool too_low = false
	for var int i = 0 to roof
		var float low_curr = low[i]

		if low_curr < lower_low
			lower_low := low_curr

			too_low := true

			break

	var color valid = color.white
	if too_low == true
		valid := color.red

	line.new(last_bar_index, low[0], last_bar_index - roof, low[roof], color = valid)

	label.new(last_bar_index, low[0], str.tostring(low[0]), color = valid)
	label.new(last_bar_index - roof, low[roof], str.tostring(low[roof]), color = valid)
