//@version=6
indicator("downtrend")

var roof = input.int(100, "Roof", minval = 1, maxval = 300000)

if barstate.islast
	var float lower_low = low[roof]
	var bool too_low = false
	for var int i = 0 to roof
		var float low_curr = low[i]

		if low_curr < lower_low
			lower_low := low_curr

			too_low := true

			break

	var color valid = color.white
	if too_low == true
		valid := color.red

	line.new(bar_index, low, bar_index - roof, low[roof], color = valid)

	label.new(bar_index, low, str.tostring(low), color = valid)
	label.new(bar_index - roof, low[roof], str.tostring(low[roof]), color = valid)
