//@version=6
library("err")

export enum Err
	idx_neg
	idx_small
	ln_neg

fmt(string msg) =>
	log.error(str.format("Error: {0}", msg))

export print(Err e) =>
	switch e
		Err.idx_neg => fmt("Index not natural number")
		Err.idx_small => fmt("Index too small to accomodate size of pattern")
		Err.ln_neg => fmt("Length not natural number")

		=> fmt(str.format("Invalid error code \"{0}\"", str.tostring(e)))
