//@version=6
library("lvl")

import JackisaDayTrader/err/1
import JackisaDayTrader/name/1

string[] h_alt = array.new<string>()
h_alt.push("H")
Alt h = Alt.new("High", h_alt)

string[] l_alt = array.new<string>()
l_alt.push("L")
Alt l = Alt.new("Low", l_alt)

export type Tag
	float lvl
	string str

export high(int lookback) =>
	if lookback < 0
		err.print_enum(err.Err.idx_neg)

		na

	Tag.new(high[ta.highestbars(high, lookback)], alt.alt_fmt(h))

export low(int lookback) =>
	if lookback < 0
		err.print_enum(err.Err.idx_neg)

		na

	Tag.new(low[ta.lowestbars(low, lookback)], alt.alt_fmt(l))
