//@version=6
library("lvl")

import JackisaDayTrader/err/1
import JackisaDayTrader/name/1

string[] h_alt = array.new<string>()
h_alt.push("H")
Name h = Name.new("High", h_alt)

string[] l_alt = array.new<string>()
l_alt.push("L")
Name l = Name.new("Low", l_alt)

export type Tag
	float lvl
	string str

export high(int offset) =>
	if offset < 0
		err.print(err.Err.idx_neg)

		na

	Tag.new(high[ta.highestbars(high, offset)], name.name_fmt(h))

export low(int offset) =>
	if offset < 0
		err.print(err.Err.idx_neg)

		na

	Tag.new(low[ta.lowestbars(low, offset)], name.name_fmt(l))
