//@version=6
library("trend")

import JackisaDayTrader/err/1

export type Seg
	int l
	int l_lvl
	int r
	int r_lvl
	string str

export up(int offset) =>
	if offset < 0
		err.print(err.Err.idx_neg)

		na

	if offset < 1
		err.print(err.Err.idx_small)

		na

	if low <= low[offset]
  	na

	for var int i = 1 to offset
		if low <= low[i]
			na

	Seg.new(bar_index, low, bar_index[offset], low[offset], "Uptrend")

export down(int offset) =>
	if offset < 0
		err.print(err.Err.idx_neg)

		na

	if offset < 1
		err.print(err.Err.idx_small)

		na

	if high >= high[offset]
		na

	for var int i = 1 to offset
		if high >= high[i]
			na

	Seg.new(bar_index, high, bar_index[offset], high[offset], "Downtrend")
