//@version=6
indicator("Trendline", overlay = true)

if bar_index == last_bar_index
    const int roof = 30

    var float lower_low = low[roof]
    var bool too_low = false
    for var int i = 0 to roof
        var float low_curr = low[i]

        if low_curr < lower_low
            lower_low := low_curr

            too_low := true

            break

    var float old_high = low[roof]
    var int old_bar_idx = last_bar_index - roof
    var float last_high = low[0]

    var color valid = color.blue
    if too_low == true
        valid := color.red

    line.new(last_bar_index, last_high, old_bar_idx, old_high, color = valid)
