//@version=6
library("util")

export body_floor(int idx) =>
	math.min(open[idx], close[idx])

export body_roof(int idx) =>
	math.max(open[idx], close[idx])
    
export wick_floor(int idx) =>
	math.min(high[idx], low[idx])

export wick_roof(int idx) =>
	math.max(high[idx], low[idx])

export body(int idx) =>
	floor = body_floor(idx)
	roof = body_roof(idx)
	[floor, roof]
    
export wick(int idx) =>
	floor = wick_floor(idx)
	roof = wick_roof(idx)
	[floor, roof]
