//@version=6
library("zone")

import JackisaDayTrader/err/1

export type Zone
	int start
	int end
	float floor
	float roof

export gap(int lookback) =>
	if lookback < 0
		err.print(err.Err.idx_neg)

		na

	if lookback < 2
		err.print(err.Err.idx_small)

		na

	float close_fst = close[lookback]
	float open_snd = open[lookback - 1]

	math.max(close_fst, open_snd) < math.min(close_fst, open_snd)

export gap_up(int lookback) =>
	if lookback < 0
		err.print(err.Err.idx_neg)

		na

	if lookback < 2
		err.print(err.Err.idx_small)

		na

	close[lookback] < open[lookback - 1]

export gap_down(int lookback) =>
	if lookback < 0
		err.print(err.Err.idx_neg)

		na

	if lookback < 2
		err.print(err.Err.idx_small)

		na

	close[lookback] > open[lookback - 1]
