//@version=6
library("zone")

import JackisaDayTrader/err/1

export type Zone
	int start
	int end
	float floor
	float roof

export gap(int offset) =>
	if offset < 0
		err.print(err.Err.idx_neg)

		na

	if offset < 2
		err.print(err.Err.idx_small)

		na

	float close_fst = close[offset]
	float open_snd = open[offset - 1]

	math.max(close_fst, open_snd) < math.min(close_fst, open_snd)

export gap_up(int offset) =>
	if offset < 0
		err.print(err.Err.idx_neg)

		na

	if offset < 2
		err.print(err.Err.idx_small)

		na

	close[offset] < open[offset - 1]

export gap_down(int offset) =>
	if offset < 0
		err.print(err.Err.idx_neg)

		na

	if offset < 2
		err.print(err.Err.idx_small)

		na

	close[offset] > open[offset - 1]
