//@version=6
library("zone")

import JackisaDayTrader/err/1

export type Zone
	int start
	int end
	float floor
	float roof

export gap(int lookback) =>
	if lookback < 0
		err.print_enum(err.Err.idx_neg)

		na

	if lookback < 2
		err.print_enum(err.Err.idx_small)

		na

	for var int i = 0 to lookback
		var int i_fst = i + 1
		if close[i_fst] < open[i]
			Zone.new(bar_index[i_fst], bar_index[i], open[i_fst], open[i])

			break

	na
